### ISSUE TITLE
Non-interactive mode works incorrectly

### ISSUE THREAD

**Issue by Boodoochai** [MeerkatBoss/quadratic-equation#1]
**Describe the bug**
Non-interactive mode of the program gives wrong answer.

**To Reproduce**
1. Run the program with this command line arguments: "1 1 1"
2. See error

**Expected behavior**
The program should output: "No real roots".

**Screenshots**
![image](https://user-images.githubusercontent.com/91817242/187176634-7914bcb0-cf74-4e11-a92f-64a8ff64e24f.png)

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser: yandex-bowser
 - Version 5.19.4

**Comment by MeerkatBoss** [comment]
Fixed with 6eb91580953005a54b8f4361d2ed17395c82ab19
